config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :video_mixes
  resources :channels
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :taggings, as: :selectable
  has_many :tags, through: :taggings

  include BeatTag



  def mixes
    binding.pry
    # USE CASE #1: BAR OWNER CHOSE GENRES AND ERAS BUT LEFT OCCASION AND SUBTAGS EMPTY

    # USE CASE #2: BAR OWNER CHOSE GENRES BUT LEFT ERAS, OCCASION, AND SUBTAGS EMPTY

    # USE CASE #3: BAR OWNER CHOSE ERAS BUT LEFT GENRES, OCCASION, AND SUBTAGS EMPTY

    # USE CASE #4: BAR OWNER CHOSE EITHER OCCASION OR SUBTAGS BUT LEFT ERAS AND GENRES EMPTY

    # USE CASE #5: BAR OWNER CHOSE EVERYTHING! (GENRES, ERAS, OCCASIONS, SUBTAGS)
    # VideoMix.where(tag_ids: c.tag_ids)
    VideoMix.all.each do |video_mix|
      if video_mix.tag_ids == self.tag_ids

      end
    end

    # VideoMix.where()
  end
end

app/models/concerns/beat_tag.rb
module BeatTag

  def grouped_tags
    self.tags.group_by(&:type)
  end

  def era_ids
    self.grouped_tags["Era"].pluck(:id)
  end

  def genre_ids
    self.grouped_tags["Genre"].pluck(:id)
  end

  def occasion_ids
    self.grouped_tags["Occasion"].pluck(:id)
  end

  def subtag_ids
    self.grouped_tags["Subtag"].pluck(:id)
  end

end

app/models/era.rb
class Era < Tag

end

app/models/genre.rb
class Genre < Tag

end

app/models/occasion.rb
class Occasion < Tag

end

app/models/subtag.rb
class Subtag < Tag

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings

  # def self.genres
  #   where(type: 'Genre')
  # end
  #
  # def eras
  # end
  #
  # def occasions
  # end
  #
  # def subtags
  # end

end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :selectable, polymorphic: true
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  has_many :taggings, as: :selectable
  has_many :tags, through: :taggings

end

app/models/video_mix.rb
class VideoMix < ApplicationRecord
  has_many :taggings, as: :selectable
  has_many :tags, through: :taggings

  include BeatTag
  # https://apidock.com/rails/ActiveRecord/Associations/CollectionAssociation/ids_writer

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel, only: [:show, :edit, :update]

  def index
    # @channels = Channel.all
    @channels = Channel.joins(:tags).group('tags.name')
  end

  # Channel.joins(:tags).where('tags.type = ?', 'Genre').group('tags.name').count
  # Channel.joins(:tags).where('tags.name = ?', 'Country')

  def show
  end

  def new
    @channel = Channel.new
    @tags = Tag.all.group_by(&:type)
  end

  def edit
    @tags = Tag.all.group_by(&:type)
  end

  def create
    @channel = Channel.new(channel_params)
    @channel.save
    redirect_to channels_path
  end

  def update
    @channel.update(channel_params)
    redirect_to channels_path
  end

  private

    def set_channel
      @channel = Channel.find(params[:id])
    end

    def channel_params
      params.require(:channel).permit(:name, tag_ids: [])
    end

end

app/controllers/video_mixes_controller.rb
class VideoMixesController < ApplicationController
  before_action :set_video_mix, only: [:show, :edit, :update]

  def index
    @video_mixes = VideoMix.all
  end

  def show
  end

  def new
    @video_mix = VideoMix.new
    @tags = Tag.all.group_by(&:type)
    # @subtags = Subtag.all
  end

  def edit
    @tags = Tag.all.group_by(&:type)
  end

  def create
    @video_mix = VideoMix.new(video_mix_params)
    @video_mix.save
    redirect_to video_mixes_path
  end

  def update
    @video_mix.update(video_mix_params)
    redirect_to video_mixes_path
  end

  private

    def set_video_mix
      @video_mix = VideoMix.find(params[:id])
    end

    def video_mix_params
      # binding.pry
      params.require(:video_mix).permit(:name, tag_ids: [])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/channels/_form_checkbox.html.erb
<%= form_with model: @channel do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>

  <% ['Genre', 'Era', 'Subtag'].each do |tag_type| %>
    <h4>
      <%= tag_type.pluralize %>
    </h4>

    <% @tags[tag_type].each do |tag| %>
      <%= f.check_box(:tag_ids, { multiple: true }, tag.id, false) %>
      <%= tag.name %>
    <% end %>
  <% end %>

  <br />

  <%= f.submit %>

<% end %>

app/views/channels/_form_multiselect.html.erb
<%= form_with model: @video do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.select :genre_ids, @genres.map {|genre| [genre.name, genre.id] }, { include_hidden: false }, { multiple: true }  %>
  <%= f.submit %>
<% end %>

<!-- https://stackoverflow.com/questions/9100808/using-form-for-multi-select-fields-with-acts-as-taggable-on -->
<!-- https://stackoverflow.com/questions/8929230/why-is-the-first-element-always-blank-in-my-rails-multi-select-using-an-embedde -->

<!--
<select multiple="multiple" name="video[genre_ids][]" id="video_genre_ids">
  <option value="2">Rap</option>
  <option value="3">Punk</option>
  <option value="5">Soul</option>
</select>
-->

app/views/channels/_form_subtags.html.erb
<%= form_with model: @channel do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>

  <% ['Genre', 'Era', 'Occasion'].each do |tag_type| %>
    <h4>
      <%= tag_type.pluralize %>
    </h4>

    <% @tags[tag_type].each do |tag| %>
      <%= f.check_box(:tag_ids, { multiple: true, class: "parent-tag" }, tag.id, false) %>
      <span> <%= tag.name %> </span>
    <% end %>
  <% end %>

  <h4>
    Subtags
  </h4>

  <% @tags['Subtag'].each do |subtag| %>
    <%= f.check_box(:tag_ids, { multiple: true, class: "subtag-#{subtag.parent_id}" }, subtag.id, false) %>
    <span class="subtag-<%="#{subtag.parent_id}"%>-label"> <%= subtag.name %> </span>
  <% end %>

  <br />

  <%= f.submit %>

<% end %>

app/views/channels/edit.html.erb
<h2>Edit Channel</h2>

<%= render 'form_subtags' %>

app/views/channels/index.html.erb
at channel
<% @channels.each do |channel| %>

  <p>
    <%= link_to channel.name, edit_channel_path(channel) %>
  </p>

<% end %>

app/views/channels/new.html.erb
<h2>New Channel</h2>

<%= render 'form_subtags' %>

app/views/channels/show.html.erb
<h1><%= @channel.name %></h1>

<h3>Genres:</h3>

<%# @video_mix.genres.each do |genre| %>
  <%#= genre.name %> <br />
<%# end %>

<h3>Eras:</h3>


<br />

<%=link_to 'Edit', edit_channel_path(@channel) %> <br>
<%=link_to 'Video Index', channel_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StiSandbox</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/video_mixes/_form.html.erb
<%= form_with model: @video do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.select :genre_ids, @genres.map {|genre| [genre.name, genre.id] }, { include_hidden: false }, { multiple: true, class: "genre-multi-selector" }  %><br>
  <%= f.submit %>
<% end %>

<!-- https://stackoverflow.com/questions/9100808/using-form-for-multi-select-fields-with-acts-as-taggable-on -->
<!-- https://stackoverflow.com/questions/8929230/why-is-the-first-element-always-blank-in-my-rails-multi-select-using-an-embedde -->

<!--
<select multiple="multiple" name="video[genre_ids][]" id="video_genre_ids">
  <option value="2">Rap</option>
  <option value="3">Punk</option>
  <option value="5">Soul</option>
</select>
-->

<!-- <select class="js-example-basic-multiple" name="states[]" multiple="multiple">
  <option value="AL">Alabama</option>
    ...
  <option value="WY">Wyoming</option>
</select> -->

app/views/video_mixes/_form_checkbox.html.erb
<%= form_with model: @video_mix do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>

  <% ['Genre', 'Era'].each do |tag_type| %>
    <%# binding.pry %>
    <h4>
      <%= tag_type.pluralize %>
    </h4>

    <% @tags[tag_type].each do |tag| %>
      <%= f.check_box(:tag_ids, { multiple: true }, tag.id, false) %>
      <%= tag.name %>
    <% end %>



  <% end %>

  <h4>Subtags</h4>

  <% @subtags.each do |subtag| %>
    <%= f.check_box(:subtag_ids, { multiple: true }, subtag.id, false) %>
    <%= subtag.name %>
  <% end %>
  <!-- <h4> Genres </h4> -->

  <%# Genre.all.each do |genre| %>
    <%#= f.check_box(:tag_ids, { multiple: true }, genre.id, false) %>
    <%#= genre.name %>
  <%# end %>

  <!-- <h4> Eras </h4> -->

  <%# Era.all.each do |era| %>
    <%#= f.check_box(:tag_ids, { multiple: true }, era.id, false) %>
    <%#= era.name %>
  <%# end %>



  <%= f.submit %>
<% end %>

app/views/video_mixes/_form_subtags.html.erb
<%= form_with model: @video_mix do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>

  <% ['Genre', 'Era', 'Occasion'].each do |tag_type| %>
    <h4>
      <%= tag_type.pluralize %>
    </h4>

    <% @tags[tag_type].each do |tag| %>
      <%= f.check_box(:tag_ids, { multiple: true, class: "parent-tag" }, tag.id, false) %>
      <span> <%= tag.name %> </span>
    <% end %>
  <% end %>

  <h4>
    Subtags
  </h4>

  <% @tags['Subtag'].each do |subtag| %>
    <%= f.check_box(:tag_ids, { multiple: true, class: "subtag-#{subtag.parent_id}" }, subtag.id, false) %>
    <span class="subtag-<%="#{subtag.parent_id}"%>-label"> <%= subtag.name %> </span>
  <% end %>

  <br />

  <%= f.submit %>

<% end %>

app/views/video_mixes/edit.html.erb
<h2>Edit Video</h2>

<%= render 'form_subtags' %>

app/views/video_mixes/index.html.erb
at video index
<% @video_mixes.each do |video_mix| %>
  <p><%= link_to video_mix.name, edit_video_mix_path(video_mix) %></p>
<% end %>

app/views/video_mixes/new.html.erb
<h2>New Video Mix</h2>

<%= render 'form_subtags' %>

app/views/video_mixes/show.html.erb
<h1><%= @video_mix.name %></h1>

<h3>Genres:</h3>

<%# @video_mix.genres.each do |genre| %>
  <%#= genre.name %> <br />
<%# end %>

<h3>Eras:</h3>


<br />

<%=link_to 'Edit', edit_video_mix_path(@video_mix) %> <br>
<%=link_to 'Video Index', video_mixes_path %>